security:
#    encoders:
#        App\Entity\Admin\UserEntity:
#            algorithm: bcrypt

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\Admin\UserEntity
                property: name

    role_hierarchy:
            ROLE_EDITOR:        ROLE_USER
            ROLE_ADMIN:         ROLE_EDITOR

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            logout:
                target: /logoutSuccess
            guard:
                authenticators:
                    - app.geoserver_digest1_authenticator
            provider: app_user_provider

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
