dist: xenial

services:
    - postgresql

addons:
    postgresql: "9.5"
    apt:
        packages:
            -   postgresql-9.5-postgis-2.4

before_script:
    -   psql -U postgres -f tests/assets/sql/tdd/su.sql

matrix:
    fast_finish: true
    include:
        -   language: node_js
            sudo: false
            node_js:
                - "9"
                - "8"
            script:
                - yarn test:unit

        -   language: php
            sudo: false
            php:
                -   "7.1"
                -   "7.2"
            env:
                -   COVERAGE=true PHPUNIT_FLAGS="--coverage-text"
                -   COMPOSER_FLAGS="--prefer-stable --prefer-lowest" SYMFONY_DEPRECATIONS_HELPER="weak_vendors"
            cache:
                directories:
                    -   $HOME/.composer/cache/files
                    -   $HOME/symfony-bridge/.phpunit
            before_install:
                -   if [[ $COVERAGE != true ]]; then phpenv config-rm xdebug.ini || true; fi
                -   if ! [ -z "$STABILITY" ]; then composer config minimum-stability ${STABILITY}; fi;
                -   if ! [ -v "$DEPENDENCIES" ]; then composer require --no-update ${DEPENDENCIES}; fi;
            install:
                -   composer update ${COMPOSER_FLAGS} --prefer-dist --no-interaction
            script:
                -   bin/phpunit --testdox -v $PHPUNIT_FLAGS
